SELECT      CUSTOMERS.CUSTOMERID, CUSTOMERS.COMPANYNAME, CUSTOMERS.CONTACTNAME, CUSTOMERS.CONTACTTITLE, CUSTOMERS.CITY, CUSTOMERS.COUNTRY,
			EMPLOYEES.LASTNAME, EMPLOYEES.FIRSTNAME, ORDERS.ORDERDATE, ORDERS.EMPLOYEEID, ORDERS.FREIGHT, ORDERS.SHIPNAME, ORDERS.SHIPADDRESS, ORDERS.SHIPCITY,
                   ORDERS.SHIPCOUNTRY, [ORDER DETAILS].ORDERID, [ORDER DETAILS].PRODUCTID, [ORDER DETAILS].UNITPRICE, [ORDER DETAILS].QUANTITY, PRODUCTS.PRODUCTNAME, PRODUCTS.UNITSINSTOCK
INTO KU
FROM         CUSTOMERS INNER JOIN
                   ORDERS ON CUSTOMERS.CUSTOMERID = ORDERS.CUSTOMERID INNER JOIN
                   EMPLOYEES ON ORDERS.EMPLOYEEID = EMPLOYEES.EMPLOYEEID INNER JOIN
                   [ORDER DETAILS] ON ORDERS.ORDERID = [ORDER DETAILS].ORDERID INNER JOIN
                   PRODUCTS ON [ORDER DETAILS].PRODUCTID = PRODUCTS.PRODUCTID
GO

INSERT	 INTO KU
SELECT * FROM KU
GO 9 --KEINE VARABLE DARIN MÖGLICH




ALTER TABLE KU ADD ID INT IDENTITY
GO



CREATE TABLE TEST1 ---
	( ID INT IDENTITY
	 ,SPX CHAR(4100)  )

INSERT INTO TEST1
SELECT 'XY'
GO 20000 ---11 / 14 / 13 / 20 SEK



CREATE TABLE TEST2
	(
		ID INT IDENTITY,
		SPX CHAR(4100)
		)

INSERT INTO TEST2
SELECT 'XY'
GO 20000

/*



*/